# html lang
# ---------------
language: default

# Main menu navigation
# ---------------
# menu:
#   Home: /
#   Archives: /archives
#   Tags: /tags
#   Categories: /categories
menu:
  主页: /
  文章: /archives
  标签: /tags
  归档: /categories
  关于: /about
# menu:
#   - page: home
#     directory: /
#     show: 首页
#   - page: archive
#     directory: /archives
#     show: 文章
#   - page: tags
#     directory: /tags
#     show: 标签
#   - page: categories
#     directory: /Categories
#     show: 归档
#   - page: about
#     directory: /about
#     show: 关于
  #XXX: /xxx

# Favicon
# ---------------
favicon: /favicon.ico?v=wang

# PWA
# ---------------
pwa:
  enable: false
  manifest: 


# Highlight theme
# ---------------
highlight_theme: default

# Nav settings
# ---------------
#social:
  #icon_name: url
social:
  github: https://github.com/jenkey2011
  weibo: https://weibo.com/747952150
  
# Algolia search
# ---------------
algolia_search:
  enable: false
  hits:
    per_page: 10
  labels:
    input_placeholder: Search for Posts
    hits_empty: "We didn't find any results for the search: ${query}"
    hits_stats: "${hits} results found in ${time} ms"

# Local search
# ---------------
local_search:
  enable: true
  labels:
    input_placeholder: 请输入关键字
    hits_empty: "未找到关于: \"${query}\" 的内容"

# MathJax
# ---------------
mathjax:
  enable: false
  cdn: https://cdn.bootcss.com/mathjax/2.7.2/MathJax.js?config=TeX-AMS-MML_HTMLorMML


# Toggle fireworks (IE >= 10)
# ---------------
fireworks: false

# Analysis
# ---------------
baidu_analytics: 5b1f88a8b8504af6901cc5ae78130e0c

google_analytics:

# stylesheets loaded in the <head>
# ---------------
stylesheets:
- /css/index.css

# scripts loaded in the end of the body
# ---------------
scripts:
- /js/utils.js
- /js/fancybox.js
- /js/sidebar.js
- /js/copy.js
- /js/fireworks.js
- /js/transition.js
- /js/scroll.js
- /js/head.js
- /js/busuanzi.pure.mini.js

# cdn for third-party library
# ---------------
cdn:
  css:
    fontawesome: https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css
  js:
    anime: /js/third-party/anime.min.js
    jquery: /js/third-party/jquery.min.js
    fancybox: /js/third-party/jquery.fancybox.min.js
    velocity: /js/third-party/velocity.min.js 
    velocity-ui: /js/third-party/velocity.ui.min.js 

# Post info settings
# ---------------
avatar: https://avatars3.githubusercontent.com/u/20010737?s=460&v=4

top_img: https://uploadbeta.com/api/pictures/random/?key=BingEverydayWallpaperPicture # false or url of img 

post_meta:
  date_type: created # created or updated 
  categories: true
  tags: true

wordcount:
  enable: true

toc:
  enable: true

post_copyright:
  enable: true
  license: CC BY-NC-SA 3.0
  license_url: https://creativecommons.org/licenses/by-nc-sa/3.0/

QR_code:
  - itemlist:
      img: ../../../../img/alipay.jpg
      text: 支付宝
  - itemlist:
      img: ../../../../img/wechat.jpg
      text: 微信

# adv:
  # enable: false
  # info: 

# Share System
# ---------------
addThis:
  enable: false
  #pubid: 

sharejs:
  enable: true
  disabled_sites: 

# Comments System
# ---------------
disqus:
  enable: false 
  #shortname: 
  #count: 

laibili:
  enable: true
  uid: MTAyMC8zNDMzMC8xMDg2Nw==

# gitment
  # enable: false
  # owner: 
  # repo: 
  # client_id: 
  # client_secret: 

# gitalk:
#   enable: false
#   client_id: 
#   client_secret: 
#   repo: gitalkBlog
#   owner: zouyaoji
#   admin: zouyaoji

# valine comment system. https://valine.js.org
valine:
  enable: false # if you want use valine,please set this value is ture
  appId:  # leancloud application app id
  appKey:  # leancloud application app key
  notify: false # valine mail notify (true/false) https://github.com/xCss/Valine/wiki
  verify: false # valine verify code (true/false)
  pageSize: 10 # comment list page size
  avatar: mm # gravatar style https://valine.js.org/#/avatar
  lang: zh-cn # i18n: zh-cn/en
  placeholder: Just go go # valine comment input placeholder(like: Please leave your footprints )
  guest_info: nick,mail,link #valine comment header inf

# Footer Settings
# ---------------
since: 2016

ICP:
  enable: false
  #text: 

# busuanzi count for PV / UV in site
busuanzi:
  # count values only if the other configs are false
  enable: true
  # custom uv span for the whole site
  site_uv: true
  site_uv_header: 本站访客数
  site_uv_footer:
  # custom pv span for the whole site
  site_pv: true
  site_pv_header: 本站总访问量
  site_pv_footer:
  # custom pv span for one page only
  page_pv: true
  page_pv_header: 本文总阅读量
  page_pv_footer:


# Sidebar Settings
# ---------------
#links_title: Links
#links:
  #Name: url
